version: "3"

services: 
  app:
    build: .
    ports:
      - "3333:5000"
    container_name: app
    volumes:
      - ../app:/usr/src/app
    environment:
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    tty: true